### ISSUE TITLE
Hubot app does not accept direct messages

### ISSUE THREAD

**Issue by stephenyeargin** [hubot-friends/hubot-slack#25]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version: `@hubot-friends/hubot-slack`

node version: v16

OS version(s): macOS

#### Steps to reproduce:

1. Attempt to DM the bot
2. Observe a `channel_not_found` error

#### Expected result:

The prior version of the bot would respond to DMs. Convenient for quick messages that are specific to the actor.

#### Actual result:

```
{"level":50,"time":1693442972225,"pid":11312,"hostname":"Stephens-Mini.home.yearg.in","name":"Hubot","err":{"type":"Error","message":"An API error occurred: channel_not_found","stack":"Error: An API error occurred: channel_not_found\n  at platformErrorFromResult (/Users/stephen/Sites/yeargin-hubot/node_modules/@slack/web-api/dist/errors.js:56:33)\n  at WebClient.apiCall (/Users/stephen/Sites/yeargin-hubot/node_modules/@slack/web-api/dist/WebClient.js:181:56)\n  at processTicksAndRejections (node:internal/process/task_queues:95:5)\n  at Function.all (<anonymous>:null:null)\n","code":"slack_webapi_platform_error","data":{"ok":false,"error":"channel_not_found","response_metadata":{"scopes":["identify","read","post","client","apps"],"acceptedScopes":["channels:read","groups:read","mpim:read","im:read","read"]}}},"msg":"Dropping message due to error An API error occurred: channel_not_found"}
```

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by joeyguerra** [comment]
I am unable to reproduce this bug with Node v16.20.2 and `@hubot-friends/hubot-slack@1.0.9`.

One thing to check is the Slack App scopes. The one I've setup has the following Scopes:

```json
"scopes": [
        "app_mentions:read",
        "channels:history",
        "channels:join",
        "channels:read",
        "channels:write.topic",
        "chat:write",
        "commands",
        "files:read",
        "files:write",
        "groups:history",
        "users:write",
        "links:read",
        "im:history",
        "im:read",
        "reactions:read",
        "reactions:write",
        "groups:read",
        "mpim:read",
        "emoji:read",
        "users:read",
        "mpim:history"
      ]
```

**Comment by joeyguerra** [comment]
I see now. The bot is started with `--alias` and the code is not taking that into consideration. Thanks for reporting this.
